### ISSUE TITLE
[BUG] Battery icon padding

### ISSUE THREAD

**Issue by nanodan52** [DHD2280/Oxygen-Customizer#1]
### Describe the bug

Hello, 
First off, absolutely incredible app, in love with it. Great work. It's exactly what I was looking for for my OnePlus 12.
Now, I'm seeing some weird behavior around the battery icon and percentage in the status bar. Upon installing and enabling the app, the text percentage to the right of the icon came back even with that option set to disabled/inside the icon in the official OOS settings. In order to disable the percentage text to the right of the battery icon, I had to enable custom battery icon and manually configure to move battery percent to within the icon in this app. However, now I have a large gap between my battery icon and the remaining status bar icons, and even if I disable a custom battery icon, the padding issue persists. I can't figure out how to remove the gap. Screenshots attached. 

### Steps to reproduce

See issue description. 

### Expected behavior

No padding issue, and no outside percentage text / respect system settings if custom battery icon is disabled within this app

### Screenshots

![Screenshot_2024-04-23-09-57-02-74_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/DHD2280/Oxygen-Customizer/assets/6110208/54ae7a96-930d-4920-9d0d-781eba37602c)
![Screenshot_2024-04-23-09-56-47-50_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/DHD2280/Oxygen-Customizer/assets/6110208/2e5cb004-e5c1-4a38-9430-e10dea71e01a)

### Device information

- Device:  OnePlus 12
- OS: latest oos 14 
- App version: v1.0.1

**Comment by DHD2280** [comment]
Hello.
Thanks for the report.
The issue with battery text is fixed.
I'm doing other stuff then will publish the new release.
For the padding restart SystemUI.
Sometimes enabling/disabling battery icon needs to restart SystemUI. Will add a dialog or a self restart.
Please wait for the new release and let me know.

**Comment by nanodan52** [comment]
> Hello. Thanks for the report. The issue with battery text is fixed. I'm doing other stuff then will publish the new release. For the padding restart SystemUI. Sometimes enabling/disabling battery icon needs to restart SystemUI. Will add a dialog or a self restart. Please wait for the new release and let me know.

Thanks for the reply. Glad to hear that bug has been worked out. 
I did try a system UI restart as well as a full system restart to try to clear the padding issue, and it is still there. I tried restarting after disabling custom batter icon as well which didn't fix it. 

I'll patiently wait for the update and when it is available try again. 

thanks for everything!

**Comment by DHD2280** [comment]
Please try the new release and let me know!

**Comment by nanodan52** [comment]
> Please try the new release and let me know!

It is all fixed! Thanks! Really appreciate you making this. Can you add a donation link to the github?

**Comment by DHD2280** [comment]
Thanks!
The donation link is in the homepage, in [FAQ](https://github.com/DHD2280/Oxygen-Customizer?tab=readme-ov-file#-faq).

Anyway I will add a little banner for donations :)
