### ISSUE TITLE
[BUG] Advanced reboot function has no effect

### ISSUE THREAD

**Issue by HsiehYifang** [DHD2280/Oxygen-Customizer#2]
### Describe the bug

Advanced reboot function has no effect。

### Steps to reproduce

Clicking the reboot option has no actual effect

### Expected behavior

Clicking the reboot option has no actual effect

### Device information

- Device: OnePlus 10 pro
- OS: Oxygen OS 14 with update 14.0.0.600
- App version:  v1.1.0

**Comment by DHD2280** [comment]
Hello.
Thanks for the report.
Can you provide xposed logs?
Open the power menu, tap on the advanced reboot button and save logs from xposed.
Thanks

**Comment by HsiehYifang** [comment]
Does it need to turn off xposed API call protection?
[LSPosed_2024-04-25T14_47_03.418045.zip](https://github.com/DHD2280/Oxygen-Customizer/files/15105645/LSPosed_2024-04-25T14_47_03.418045.zip)

**Comment by HsiehYifang** [comment]
Does it need to turn off xposed API call protection?
[Uploading LSPosed_2024-04-25T14_47_03.418045 (1).zip…]()

**Comment by DHD2280** [comment]
Please, can you reupload? I can't download it.
Thanks

**Comment by HsiehYifang** [comment]
[LSPosed_2024-04-25T14_47_03.418045 (1).zip](https://github.com/DHD2280/Oxygen-Customizer/files/15107090/LSPosed_2024-04-25T14_47_03.418045.1.zip)

**Comment by DHD2280** [comment]
Hello, I can't see any error in logs, can you please try latest beta?
[Here](https://github.com/DHD2280/Oxygen-Customizer/releases/tag/beta_builds)
Thanks

**Comment by HsiehYifang** [comment]
> Hello, I can't see any error in logs, can you please try latest beta? [Here](https://github.com/DHD2280/Oxygen-Customizer/releases/tag/beta_builds) Thanks

Still has no function

**Comment by DHD2280** [comment]
Excuse me, can you show the problem with a screen record?
Thanks

**Comment by DHD2280** [comment]
Are you using Kernel SU?
If yes, this bug should be solved, I will upload a new build soon.

**Comment by HsiehYifang** [comment]
> Are you using Kernel SU? If yes, this bug should be solved, I will upload a new build soon.

yes

**Comment by DHD2280** [comment]
Hello, can you try latest beta?
[Here](https://github.com/DHD2280/Oxygen-Customizer/releases/tag/beta_builds)
Thank you

**Comment by HsiehYifang** [comment]
Still not working, and there is also a bug in the color displayed by the
clock.


DHD2280 ***@***.***> 於 2024年5月1日 週三 06:44 寫道：

**Comment by DHD2280** [comment]
Hi.
Can you please contact me on telegram? So I can investigate better.
Thank you

**Comment by HsiehYifang** [comment]
My English is weak, I'm afraid I can't be of much help.

DHD2280 ***@***.***> 於 2024年5月1日 週三 16:58 寫道：

**Comment by HsiehYifang** [comment]
it's working

**Comment by DHD2280** [comment]
If anyone is facing the same issue: please ensure that you granted root permissions to SystemUI.
